// This file is autogenerated. Changes will be overwritten.
#include <IV26G72HR5/moc_battlesystem.cpp>
#include <PRMOGMWJPH/moc_gameengine.cpp>
#include <YPKJ5OE7LN/moc_battlescene.cpp>
#include <YPKJ5OE7LN/moc_loadgamedialog.cpp>
#include <YPKJ5OE7LN/moc_mainwindow.cpp>
#include <YPKJ5OE7LN/moc_preparescene.cpp>
#include <YPKJ5OE7LN/moc_savegamedialog.cpp>
